name: Bug tracker

on:
  workflow_dispatch:
  issues:
    types: labeled

jobs:
  get-org-repos:
    runs-on: ubuntu-latest
    steps:
      - uses: austenstone/get-org-repos@main
        with:
          github-token: ${{ secrets.PROJECT_PAT }}
        id: get-org-repos
    outputs:
      repos: ${{ steps.get-org-repos.outputs.repos }}
      
  run-for-each-repo:
    needs: get-org-repos
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ${{ fromJson(needs.get-org-repos.outputs.repos) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.organization.login }}/${{ matrix.repo }}
          token: ${{ secrets.PROJECT_PAT }}

      - name: Add to Project if Label is 'bug'
        if: contains(github.event.issue.labels.*.name, 'bug')
        uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/orgs/fairpm/projects/5
          github-token: ${{ secrets.PROJECT_PAT }}
